### PR TITLE
matmul chain optimize

### PR DESCRIPTION
**Pull request by commander-trashdin**
I have no idea about your style so I am totally ready to move those functions around or merge them together etc. Just tell me the convention you use.

Signed-off-by: thrashdin <aun.sokolov@gmail.com>

### CODE REVIEW

**Comment by guicho271828** [comment]
I will perform some documentation work and change the style if necessary.

**Comment by guicho271828** [comment]
Thank you very much for your effort.

**Comment by guicho271828** [comment]
Did you consult any literature while developping this? If so, please give me the reference so that I can cite from the source code

**Comment by guicho271828** [comment]
Reading the code, you don't seem to understand how compiler-macro works, so I need to rewrite it.

Since it has to run in the runtime, some list-manipulation routines will be turned into structs.

**Comment by guicho271828** [comment]
It seems working as expected. I renamed `fast-matmul` to `matmul*` (i.e. multi-arg version of `matmul`) and turned it into a function. Some optimization could be done, but thanks!

```lisp
(defun test3 ()
  (let ((*print-array* nil))
    (time (print
           ;; naive approach will generate a 1000x1000 intermediate matrix
           (matmul* (zeros '(1000 1) :type 'fixnum)
                    (zeros '(1 1000) :type 'fixnum)
                    (zeros '(1000 1000) :type 'fixnum)))))
  nil)

;; Results

#|

Environment: sbcl 1.5.9, RYZEN 1700

* Naive

IMPL> (test3)

#<(ARRAY FIXNUM (1000 1000)) {1004500D1F}> 
Evaluation took:
  4.646 seconds of real time
  4.643399 seconds of total run time (4.635514 user, 0.007885 system)
  99.94% CPU
  6 forms interpreted
  410 lambdas converted
  13,910,318,070 processor cycles
  30,318,096 bytes consed
  
NIL



* proposed

IMPL> (test2)

(MATMUL #<(ARRAY FIXNUM (1000 1)) {1005BC1F5F}>
        (MATMUL #<(ARRAY FIXNUM (1 1000)) {1005BC3F9F}> #<(ARRAY FIXNUM (1000 1000)) {1005BC408F}>)) 
Evaluation took:
  0.003 seconds of real time
  0.002612 seconds of total run time (0.002612 user, 0.000000 system)
  100.00% CPU
  7,659,570 processor cycles
  8,025,856 bytes consed
  
NIL

|#
```

**Comment by guicho271828** [comment]
oops, no, it is not doing what it should do.

**Comment by guicho271828** [comment]
This time it should be correct.

```lisp
* proposed

IMPL> (test3)

#<(ARRAY FIXNUM (1000 1000)) {1003C3046F}> 
Evaluation took:
  0.032 seconds of real time
  0.031556 seconds of total run time (0.031556 user, 0.000000 system)
  100.00% CPU
  6 forms interpreted
  410 lambdas converted
  95,227,980 processor cycles
  22,308,112 bytes consed
  
NIL
```

**Comment by commander-trashdin** [comment]
No, I came up with this one myself and then maybe only checked the wiki page.

There's more efficient approach by Hu and Shiny (link also here https://en.m.wikipedia.org/wiki/Matrix_chain_multiplication) which I was planning to implement as well, but it's reeeally long and hard, so I had to leave it for now, this summer I'll probably get to it.

I was also working on similar upgrade for tensors, but this one is much harder and -- in case of dynamic solution -- much much slower, up to exponential, depending on how exactly tensors are contracted.  There might be solution for tensors similar to what H&S did, and I'd like to think about that too, but this is almost on a thesis level.

**Comment by commander-trashdin** [comment]
PS it would be cool (not sure how possible), to detect and change reduce with standard matmul into apply of matmul*. Not sure if worth the effort, but my understanding is that reduce is what people usually use.

**Comment by guicho271828** [comment]
thanks for the reference. I am more interested... in particular, I did not realize that it generalizes to string concatenation (noted at the bottom).
I might implement the Hu-Shiny method myself.

**Comment by commander-trashdin** [comment]
Right, but for strings it is (as noted) not really useful, as there is a better way.

2 notes I wanna leave:
1. One of the things I struggled with is I had to use weird lists in my impl, just because there are no local structs, and I was trying to avoid creating any sort of named struct to not clash with existing ones. However...maybe you can think of any workaround, and that and also maybe optimizing my small functions ( I made them _somehow_ because atm I preferred to understand my code rather then make it fast) will make my solution, well, faster, and probably cons less. But still the same O(n^3).

2. It is really simple for tensors (modulo the lists/structs for some intermediate data will get even uglier) because instead of just one line there's a graph there (unfortunately not always a tree), and I think using DP and solving it for all subgraphs will be successful albeit very slow. However! if this is done at compile time, then it's not a big deal. Looking at the code (only got a chance to do it now) I am not sure if there's any compile-time calculations going on? anyway its good.


P.S. Thank you so much, this is the first time I got a pr into an open source, it really lifted my spirit.

**Comment by guicho271828** [comment]
I will probably implement the DP on wikipedia. It looks simple: It just scans the range and update the array.

**Comment by guicho271828** [comment]
DP: the O(n^2) one.

To run this algorithm in the compile time you need to know the shape at compile time. This rarely happens and also fetching the information must be done through cltl2. You need to understand what I am saying to implement it.

**Comment by commander-trashdin** [comment]
Oh, right it is O(n^2). My n^3 was too rough of an estimation, now as I think of it.

I am pretty confident I understand what you are saying, which is why I mentioned compile time calculations -- numcl explicitly states in the description that arrays used are specialized, so chances of getting their dimensions out with cltl2 are higher?

I m just not good at it, even the compiler macro you saw and removed wasn't mine, I asked a friend to help me write it, but it seems we both are too bad:)) So I didn't try to go even deeper (you meant something like this should be used right https://github.com/alex-gutev/cl-environments)

**Comment by guicho271828** [comment]
I just implemented the O(n^2) DP. Below is the result of multiplying a randomly generated sequence of 10 or 20 medium-sized arrays. It turned out the DP is much faster, especially because it just uses arrays (not playing around with cons cells). See code here: https://github.com/numcl/numcl/blob/master/src/4linear-algebra3.lisp .

I understand running matmul* with 10 or 20 arrays is rare, but the additional benefit is that the code is also much simpler than your version (just 2 functions). The code is an almost line-by-line translation from C.

I believe implementing O(n log n) DP is an overkill and I don't feel the need of it.

```
###############################
#### test 3-1 : optimization runtime -- 10 arrays
###############################

#<FUNCTION MATMUL*> 
#<(ARRAY FIXNUM (10 910)) {10019C1C9F}> 
Evaluation took:
  0.070 seconds of real time

#<FUNCTION MATMUL*-THRASHDIN> 
#<(ARRAY FIXNUM (10 910)) {10017C1C9F}> 
Evaluation took:
  0.666 seconds of real time

#<FUNCTION MATMUL*-NAIVE> 
#<(ARRAY FIXNUM (10 910)) {10018C1C9F}> 
Evaluation took:
  0.068 seconds of real time

###############################
#### test 3-2 : optimization runtime -- 20 arrays
###############################

#<FUNCTION MATMUL*> 
#<(ARRAY FIXNUM (960 910)) {1001A6311F}> 
Evaluation took:
  0.175 seconds of real time

#<FUNCTION MATMUL*-THRASHDIN> 
#<(ARRAY FIXNUM (960 910)) {1001DE6F9F}> 
Evaluation took:
  2.298 seconds of real time

#<FUNCTION MATMUL*-NAIVE> 
#<(ARRAY FIXNUM (960 910)) {10018B271F}> 
Evaluation took:
  11.991 seconds of real time
```

**Comment by commander-trashdin** [comment]
Well okay, the wiki one is better then me and I think I understand where. Anyway I am glad that I at least inspired you to so this. I'll still be working on similar thing for tensordot.

**Pull request merged**
