### PR TITLE
Fixes issue #51

### LINKED ISSUE #51: (arange -10 10 3) => #(-10 -7 -4 -1 2 5) ?
(arange -10 10 3) should be #(-10 -7 -4 -1 2 5 8) but #(-10 -7 -4 -1 2 5)

### PR DESCRIPTION
**Pull request by mparlaktuna**
Signed-off-by: Mustafa Parlaktuna   <mparlaktuna@gmail.com>
Fixes #51 
0 was not counted during length calculation for arange. I added a calculate-range function to check the signs of start, stop and difference. Tested with the arange function calls inside example.lisp

### CODE REVIEW

**Comment by mparlaktuna** [comment]
By the way I had to remove file 5reduce to be able to compile locally. It crashes with 
`fatal error encountered in SBCL pid 7860(tid 0x7f7109b532c0):
Heap exhausted, game over.`
That might be the reason Travis CI is failing.

**Comment by guicho271828** [comment]
hi, thanks for the patch.

> fatal error encountered in SBCL pid 7860(tid 0x7f7109b532c0): Heap exhausted, game over.

This is related to the default sbcl heap size. Give `dynamic-space-size=8000` when you launch sbcl.

**Comment by guicho271828** [comment]
The patch does not seem to account for the cases where start/stop are floats or other number types.
this might be the cause of these regressions:
https://travis-ci.org/github/numcl/numcl/jobs/759123203#L444
https://travis-ci.org/github/numcl/numcl/jobs/759123202#L543

**Comment by guicho271828** [comment]
if it is fixed, then please consider making `calculate-range` inline.

**Comment by guicho271828** [comment]
another thing I can think of is to add failure cases to the tests.

**Comment by mparlaktuna** [comment]
Thanks for the suggestions. I think I got it fixed. What type of failure cases were you thinking about?

**Comment by mparlaktuna** [comment]
I started writing some tests and realized it is not fixed yet. I will continue working on it.

**Pull request closed without merging**
