### PR TITLE
Static vectors support?

### PR DESCRIPTION
**Pull request by commander-trashdin**
I tried adding static vectors support. Unfortunately it seems they don't support simple arrays that are not 1d, and I'm not sure if it would be worth converting between existing 2d ones and 1d. There is only one intermediate 1s vector.

Tests are showing that some improvement takes place, but I guess it is worth trying on your machine as well to see how big it is. Also, it seems you used a lot of single floats in those matrices, which I don't fully understand. Nevertheless, if floats are needed, block-compiling this code might help with more optimizations.

### CODE REVIEW

**Comment by guicho271828** [comment]
Probably doesn't make sense to use static vectors for anything other than the backing vector

**Comment by commander-trashdin** [comment]
Isn't that what I did? I admit, I added something else as well. 


Also, it seems now (because I tried adding something else), that matmul is broken and always returns the same thing. Tested on 2 independent systems. It also doesn't always load from the first try.

**Comment by guicho271828** [comment]
No I haven't had the chance to read the comments yet

**Comment by commander-trashdin** [comment]
Don't worry, this can wait. Although broken matmul is annoying (and I suspect it it einsum in fact), should I maybe create an issue?

**Comment by guicho271828** [comment]
yes, please post the failure case.

**Comment by guicho271828** [comment]
> Although broken matmul 
I need a more detailed report.

**Comment by guicho271828** [comment]
So, this is not a full static vector support (e.g. by detecting the intermediate results in compile time etc.) but just a single modification to matmul*. Hmm.

But show me your performance comparisons.

**Comment by commander-trashdin** [comment]
Wait, I'm not sure what you mean. Without knowing dimensions at compile time (which is fine, but we've discussed it already) there isn't much to do anyway, right?

Also, I couldn't do any tests, because when I started testing I discovered the issue I submitted today.

**Comment by guicho271828** [comment]
I can't reproduce the matmul issue in my environments. I actually don't know which code is failing.

**Comment by commander-trashdin** [comment]
Yes I know, this is weird. I made sure (and just rechecked right now) the code loaded is from freshly manually downloaded numcl. What's worse. I also made a friend check it (and there's a strong guarantee he never attempted interacting with numcl in any way) -- and it fails for him as well, with both issues (hanging and nonsensical results) happening in the same manner.

**Comment by commander-trashdin** [comment]
I am sure there maybe some link between those too, because it hangs at some inlining optimization, therefore me forcebreaking it might lead to weird behavouir later.

**Comment by guicho271828** [comment]
re-reviewing this commit, I only see a temporary vector `dim` being converted to a static vector.
what it does is just making it (something similar to) a stack allocation.
I am not particularly fond of doing so just for this.

What I meant by static vector support would be done by, e.g., letting all array-making functions support an additional keyword argument, `:allocation`, which cause the backend to allocate a backing array as a static-vector.

**Pull request closed without merging**
